name: proiecttppm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_automation: ^2.0.0
  torch_controller: ^2.0.1
  flutter_sms:
    path: C:/Users/Claudia/OneDrive/Documente/GitHub/TPPM/proiect/flutter_sms-master/flutter_sms-master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
